services:
  server:
    image: ghcr.io/pxr05/audiostream:latest
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      PORT: ${PORT:-3000}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    volumes:
      - ./uploads:/usr/src/app/uploads:rw
      - ./audiostream.db:/usr/src/app/audiostream.db:rw
      - ./cookies.txt:/usr/src/app/cookies.txt:rw
    restart: unless-stopped
  yt_updater:
      build: ghcr.io/pxr05/audiostream:latest
      entrypoint: ["sh", "-c", "while true; do yt-dlp -U; sleep 86400; done"]
      restart: unless-stopped