services:
  server:
    image: ghcr.io/pxr05/audiostream:latest
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      PORT: ${PORT:-3000}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./uploads:/usr/src/app/uploads:rw
      - ./audiostream.db:/usr/src/app/audiostream.db:rw
      # - ./cookies.txt:/usr/src/app/cookies.txt:rw # only uncomment if you have cookies.txt file in the same directory
    restart: unless-stopped
  # bgutil-provider:
  #   image: brainicism/bgutil-ytdlp-pot-provider
  #   container_name: bgutil-provider
  #   ports:
  #     - "4416:4416"
  #   init: true
  #   restart: unless-stopped
